export const DATA = [
    {
        image: "/svgs/dashboard/BitcoinLogo.svg",
        token: "BTC",
        symbol: "BTC",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
    {
        image: "/svgs/dashboard/bnb.svg",
        token: "BNB",
        symbol: "BNB",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
    {
        image: "/img/strategy-crypto/ADA.png",
        token: "ADA",
        symbol: "ADA",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
    {
        image: "/img/strategy-crypto/DOGE.png",
        token: "DOGE",
        symbol: "DOGE",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
    {
        image: "/img/strategy-crypto/ETH.png",
        token: "ETH",
        symbol: "ETH",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
    {
        image: "/img/strategy-crypto/ICT.png",
        token: "ICT",
        symbol: "ICT",
        lastPrice: "$41.263,00",
        change: "+35,74%",
        marketCap: "$784,393M",
    },
];