export const TradingMarket = [
  {
    icon: "/img/strategy-crypto/BTC.png",
    name: "Bitcoin",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/ETH.png",
    name: "Ethereum",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/USDT.png",
    name: "Tether",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/BNB.png",
    name: "Binance Coin",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/ADA.png",
    name: "Cardano",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/XRP.png",
    name: "XRP",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/ICT.png",
    name: "Internet Comp",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
  {
    icon: "/img/strategy-crypto/DOGE.png",
    name: "Dogecoin",
    marketcup: "20B",
    balance: "£5.777",
    price: "0.000038",
    week: "+5.1%",
    month: "-27.4%",
    year: "+1M%",
    today: "+7.7%",
  },
];
